name: tox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        toxenv:
          - lint
          - mypy

    steps:
      - uses: actions/checkout@v2

      - name: Setup python${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install tox
        run: python -m pip install tox

      - name: tox ${{ matrix.toxenv }}
        run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
          FORCE_COLOR: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}


  tests:
    needs: lint
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - toxenv: py38
            python: "3.8"
            os: ubuntu-latest
          - toxenv: py39
            python: "3.9"
            os: ubuntu-latest
          - toxenv: py310
            python: "3.10"
            os: ubuntu-latest
          - toxenv: py311
            python: "3.11"
            os: ubuntu-latest
          - toxenv: py312
            python: "3.12"
            os: ubuntu-latest
          - toxenv: py38
            python: "3.8"
            os: windows-latest
          - toxenv: py39
            python: "3.9"
            os: windows-latest
          - toxenv: py310
            python: "3.10"
            os: windows-latest
          - toxenv: py311
            python: "3.11"
            os: windows-latest
          - toxenv: py38
            python: "3.8"
            os: macos-latest
          - toxenv: py39
            python: "3.9"
            os: macos-latest
          - toxenv: py310
            python: "3.10"
            os: macos-latest
          - toxenv: py311
            python: "3.11"
            os: macos-latest
          - toxenv: py312
            python: "3.12"
            os: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup python${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"

      - name: Install tox
        run: python -m pip install tox

      - name: tox ${{ matrix.toxenv }}
        run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
          FORCE_COLOR: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
