name: tox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        toxenv:
          - lint
          - mypy

    steps:
      - uses: actions/checkout@v2

      - name: Setup python${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install tox
        run: python -m pip install tox

      - name: tox ${{ matrix.toxenv }}
        run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
          FORCE_COLOR: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}


  tests:
    needs: lint
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - toxenv: py310
            python: "3.10"
            os: ubuntu-latest
          - toxenv: py311
            python: "3.11"
            os: ubuntu-latest
          - toxenv: py312
            python: "3.12"
            os: ubuntu-latest
          - toxenv: py313
            python: "3.13"
            os: ubuntu-latest
          - toxenv: py314
            python: "3.14"
            os: ubuntu-latest
          - toxenv: py310
            python: "3.10"
            os: windows-latest
          - toxenv: py311
            python: "3.11"
            os: windows-latest
          - toxenv: py313
            python: "3.13"
            os: windows-latest
          - toxenv: py314
            python: "3.14"
            os: windows-latest
          - toxenv: py310
            python: "3.10"
            os: macos-latest
          - toxenv: py311
            python: "3.11"
            os: macos-latest
          - toxenv: py312
            python: "3.12"
            os: macos-latest
          - toxenv: py313
            python: "3.13"
            os: macos-latest
          - toxenv: py314
            os: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup python${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"

      - name: Install tox
        run: python -m pip install tox

      - name: tox ${{ matrix.toxenv }}
        run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
          FORCE_COLOR: 1
          COVERALLS_PARALLEL: 'true'
          COVERALLS_SERVICE_NAME: github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish:
    needs:
       - tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
